# path: render.yaml  (safer defaults + healthcheck)
services:
  - type: web
    name: mirrorcore-platinum-spine
    env: node
    plan: starter
    region: ohio
    branch: main
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false            # set in Render dashboard to enforce Bearer auth
      - key: MIRRORCORE_SECRET
        generateValue: true
    healthCheckPath: /health
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
