# path: render.yaml
services:
  - type: web
    name: mirrorcore-platinum-spine
    env: node
    plan: starter
    region: ohio
    branch: main
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false              # optional: for Bearer auth if you add it later
      - key: MIRRORCORE_SECRET
        generateValue: true

    healthCheckPath: /api/heartbeat   # ✅ this is your real heartbeat route

    headers:
      - path: /*
        name: Cache-Control
        value: no-store
